# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qnp2UgIJ13W2QP2ADO2T22siF5guewL
"""

from google.colab import drive
drive.mount('/content/drive')

!git clone 'https://github.com/AlexeyAB/darknet.git' '/content/drive/My Drive/yolo/darknet'

!unzip '/content/drive/My Drive/yolo_model/custom_data.zip' -d '/content/drive/My Drive/yolo_model/'

!ls '/content/drive/My Drive/yolo_model'

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/yolo_model/darknet'

!ls

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/yolo_model

!python custom_data/creating-files-data-and-name.py

!python custom_data/creating-train-and-test-txt-files.py

!darknet/darknet detector train custom_data/labelled_data.data darknet/cfg/yolov3_custom.cfg custom_weight/darknet53.conv.74 -dont_show

